### ISSUE TITLE
Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by tneupaney** [kevoj/thispersondoesnotexist-js#1]
(function (exports, require, module, __filename, __dirname) { 'use strict';var _promise=require('babel-runtime/core-js/promise');var _promise2=_interopRequireDefault(_promise);var _assign=require('babel-runtime/core-js/object/assign');var _assign2=_interopRequireDefault(_assign);var _regenerator=require('babel-runtime/regenerator');var _regenerator2=_interopRequireDefault(_regenerator);var _asyncToGenerator2=require('babel-runtime/helpers/asyncToGenerator');var _asyncToGenerator3=_interopRequireDefault(_asyncToGenerator2);var _getPrototypeOf=require('babel-runtime/core-js/object/get-prototype-of');var _getPrototypeOf2=_interopRequireDefault(_getPrototypeOf);var _classCallCheck2=require('babel-runtime/helpers/classCallCheck');var _classCallCheck3=_interopRequireDefault(_classCallCheck2);var _createClass2=require('babel-runtime/helpers/createClass');var _createClass3=_interopRequireDefault(_createClass2);var _possibleCons

TypeError: Cannot read property 'width' of undefined
    at ThisPersonDoesNotExist._callee4 (/Users/user/Desktop/graphApi/node_modules/thispersondoesnotexist-js/dist/index.js:1:4377)
    at ThisPersonDoesNotExist.<anonymous> (/Users/user/Desktop/graphApi/node_modules/babel-runtime/helpers/asyncToGenerator.js:13:18)
    at ThisPersonDoesNotExist.getImage (/Users/user/Desktop/graphApi/node_modules/thispersondoesnotexist-js/dist/index.js:1:5575)
    at Object.getImage (/Users/user/Desktop/graphApi/fakeUsers/index.js:5:6)
    at Module._compile (module.js:653:30)
    at Module._compile (/Users/user/Desktop/graphApi/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (/Users/user/Desktop/graphApi/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**Comment by kevoj** [comment]
I'll check it out tonight :)

**Comment by Noahfreriksen** [comment]
I got this error aswell
